insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval(),'--','VATANSIZ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AD','ANDORRA PRENSLİĞİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AE','BİRLEŞİK ARAP EMİRLİKLERİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AF','AFGANİSTAN İSLAM CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AG','ANTİGUA VE BARBUDA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AL','ARNAVUTLUK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AM','ERMENİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AO','ANGOLA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AR','ARJANTİN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AS','SAMOA BAĞIMSIZ DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AT','AVUSTURYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AU','AVUSTRALYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'AZ','AZERBAYCAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BA','BOSNA HERSEK',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BB','BARBADOS',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BD','BANGLADEŞ HALK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BE','BELÇİKA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BF','BURKİNA FASO',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BG','BULGARİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BH','BAHREYN KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BI','BURUNDİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BJ','BENİN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BN','BRUNEİ DARUSSELAM',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BO','BOLİVYA ÇOKULUSLU DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BR','BREZİLYA FEDERATİF CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BS','BAHAMALAR',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BT','BUTAN KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BW','BOTSVANA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BY','BELARUS CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'BZ','BELİZE',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CA','KANADA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CD','KONGO DEMOKRATİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CG','KONGO CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CH','İSVİÇRE KONFEDERASYONU',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CI','FİLDİŞİ SAHİLİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CL','ŞİLİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CM','KAMERUN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CN','ÇİN HALK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CO','KOLOMBİYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CR','KOSTA RİKA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CS','SIRBİSTAN VE KARADAĞ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CU','KÜBA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CY','GÜNEY KIBRIS RUM YÖNETİMİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'CZ','ÇEK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DE','ALMANYA FEDERAL CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DJ','CİBUTİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DK','DANİMARKA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DM','DOMİNİKA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DO','DOMİNİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'DZ','CEZAYİR DEMOKRATİK HALK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'EC','EKVATOR CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'EE','ESTONYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'EG','MISIR ARAP CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ER','ERİTRE DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ES','İSPANYA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ET','ETİYOPYA FEDERAL DEMOKRATİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'FI','FİNLANDİYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'FJ','FİJİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'FM','MİKRONEZYA FEDERE DEVLETLERİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'FR','FRANSA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GA','GABON CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GB','BÜYÜK BRİTANYA VE KUZEY İRLANDA BİRLEŞİK KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GD','GRENADA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GE','GÜRCİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GH','GANA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GM','GAMBİYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GN','GİNE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GQ','EKVATOR GİNESİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GR','YUNANİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GT','GUATEMALA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GW','GİNE-BİSSAU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'GY','GUYANA KOOPERATİF CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'HN','HONDURAS CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'HR','HIRVATİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'HT','HAİTİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'HU','MACARİSTAN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ID','ENDONEZYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IE','İRLANDA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IL','İSRAİL DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IN','HİNDİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IQ','IRAK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IR','İRAN İSLAM CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IS','İZLANDA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'IT','İTALYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'JM','JAMAİKA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'JO','ÜRDÜN HAŞİMİ KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'JP','JAPONYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KE','KENYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KG','KIRGIZ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KH','KAMBOÇYA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KI','KİRİBATİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KK','KUZEY KIBRIS TÜRK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KM','KOMORLAR BİRLİĞİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KN','SAİNT KİTTS VE NEVİS FEDERASYONU',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KO','KOSOVA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KP','KORE DEMOKRATİK HALK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KR','KORE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KW','KUVEYT DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'KZ','KAZAKİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LA','LAOS DEMOKRATİK HALK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LB','LÜBNAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LC','SAİNT LUCİA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LI','LİHTENŞTAYN PRENSLİĞİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LK','SRİ LANKA DEMOKRATİK SOSYALİST CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LR','LİBERYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LS','LESOTHO KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LT','LİTVANYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LU','LÜKSEMBURG BÜYÜK DÜKALIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LV','LETONYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'LY','LİBYA DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'M','BİRLEŞİK MEKSİKA DEVLETLERİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MA','FAS KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MC','MONAKO PRENSLİĞİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MD','MOLDOVA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ME','KARADAĞ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MG','MADAGASKAR CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MH','MARŞAL ADALARI CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MK','MAKEDONYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ML','MALİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MM','MYANMAR BİRLİĞİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MM','BURMA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MN','MOĞOLİSTAN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MR','MORİTANYA İSLAM CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MT','MALTA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MU','MAURİTİUS CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MV','MALDİVLER CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MW','MALAVİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MY','MALEZYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'MZ','MOZAMBİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NA','NAMİBYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NE','NİJER CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NG','NİJERYA FEDERAL CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NI','NİKARAGUA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NL','HOLLANDA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NO','NORVEÇ KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NP','NEPAL FEDERAL DEMOKRATİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NR','NAURU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'NZ','YENİ ZELANDA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'OM','UMMAN SULTANLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PA','PANAMA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PE','PERU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PG','PAPUA YENİ GİNE BAĞIMSIZ DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PH','FİLİPİNLER CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PK','PAKİSTAN İSLAM CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PL','POLONYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PS','FİLİSTİN DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PT','PORTEKİZ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PW','PALAU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'PY','PARAGUAY CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'QA','KATAR DEVLETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RO','ROMANYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RS','SIRBİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / BAŞKURDİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / ALTAY CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / ADIGE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / BURYAT CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / İNGUŞETYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KABARDİN-BALKARYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KALMIKYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KARAÇAY-ÇERKES CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KARELYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KOMİ CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / MARİ EL CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / MORDOVYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / SAHA CUMHURİYETİ (YAKUTİSTAN)',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / KUZEY OSETYA-ALANYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / TATARİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / TIVA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / UDMURT CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / HAKASYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / ÇUVAŞİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / DAĞISTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FED. / ÇEÇENİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RU','RUSYA FEDERASYONU',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'RW','RUANDA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SA','SUUDİ ARABİSTAN KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SB','SOLOMON ADALARI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SC','SEYŞELLER CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SD','SUDAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SD','GÜNEY SUDAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SE','İSVEÇ KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SG','SİNGAPUR CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SI','SLOVENYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SK','SLOVAK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SL','SİERRA LEONE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SM','SAN MARİNO CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SN','SENEGAL CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SO','SOMALİ FEDERAL CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SR','SURİNAM CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ST','SAO TOME VE PRİNCİPE DEMOKRATİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SV','EL SALVADOR CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SY','SURİYE ARAP CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'SZ','SVAZİLAND KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TD','ÇAD CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TG','TOGO CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TH','TAYLAND KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TJ','TACİKİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TM','TÜRKMENİSTAN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TN','TUNUS CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TO','TONGA KRALLIĞI',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TR','TÜRKİYE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TT','TRİNİDAD VE TOBAGO CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TV','TUVALU',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TW','ÇİN TAYVAN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'TZ','TANZANYA BİRLEŞİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'UA','UKRAYNA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'UA','UKRAYNA SOV. SOS. CUM.',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'UG','UGANDA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'US','AMERİKA BİRLEŞİK DEVLETLERİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'UY','URUGUAY DOĞU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'UZ','ÖZBEKİSTAN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'VA','VATİKAN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'VC','SAİNT VİNCENT VE GRENADİNLER',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'VE','BOLİVARCI VENEZUELA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'VN','VİETNAM SOSYALİST CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'VU','VANUATU CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XA','BİLİNMEYEN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','CABO VERDE CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','ORTA AFRİKA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','DİĞER',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','KUDÜS',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','LEFKOŞA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','KIRIM',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','DOĞU TİMOR DEMOKRATİK CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','BAYLÖRUSYAN (SSC)',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','ÇEKOSLOVAKYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','DEMOKRATİK ALMANYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','YUKARI VOLTA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','SOVYET SOS.CUM.BİR.',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'XX','ZAİRE',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'YE','DEMOKRATIK YEMEN',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'YM','YEMEN CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'YU','YUGOSLAVYA',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ZA','GÜNEY AFRİKA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ZM','ZAMBİYA CUMHURİYETİ',true);
insert into adr.country (id, code,  name,enabled) values (adr.seq_country_id.nextval,'ZW','ZİMBABVE CUMHURİYETİ',true);
