package com.yil.adress.config;

import com.yil.adress.dto.CreateRegionDto;
import com.yil.adress.dto.CreateRegionTypeRequest;
import com.yil.adress.service.RegionService;
import com.yil.adress.service.RegionTypeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextStartedEvent;
import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class SetupDataLoader implements ApplicationListener<ContextStartedEvent> {

    @Autowired
    private RegionService regionService;
    @Autowired
    private RegionTypeService regionTypeService;

    @Override
    public void onApplicationEvent(ContextStartedEvent event) {
        System.out.println("Start Up Events");
        System.out.println(new Date(event.getTimestamp()));
        System.out.println("----------------------");


//        defaultRegionTypes();
    }

    private void defaultRegionTypes() {
        RegionTypeService.ulke = regionTypeService.save(CreateRegionTypeRequest.builder().name("Ülke").enabled(true).build(), 1);
        RegionTypeService.il = regionTypeService.save(CreateRegionTypeRequest.builder().name("İl").enabled(true).build(), 1);
        RegionTypeService.ilce = regionTypeService.save(CreateRegionTypeRequest.builder().name("İlçe").enabled(true).build(), 1);
        RegionTypeService.koy = regionTypeService.save(CreateRegionTypeRequest.builder().name("Köy").enabled(true).build(), 1);
        RegionTypeService.mahalle = regionTypeService.save(CreateRegionTypeRequest.builder().name("Mahalle").enabled(true).build(), 1);
        RegionTypeService.bucak = regionTypeService.save(CreateRegionTypeRequest.builder().name("Bucak").enabled(true).build(), 1);

        defaultCountries();
    }

    private void defaultCountries() {
        regionService.save(CreateRegionDto.builder().code("--").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("VATANSIZ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ANDORRA PRENSLİĞİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BİRLEŞİK ARAP EMİRLİKLERİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AF").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("AFGANİSTAN İSLAM CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ANTİGUA VE BARBUDA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ARNAVUTLUK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ERMENİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ANGOLA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ARJANTİN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAMOA BAĞIMSIZ DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("AVUSTURYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("AVUSTRALYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("AZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("AZERBAYCAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BOSNA HERSEK").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BB").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BARBADOS").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BANGLADEŞ HALK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BELÇİKA KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BF").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BURKİNA FASO").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BULGARİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BAHREYN KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BURUNDİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BJ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BENİN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BRUNEİ DARUSSELAM").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BOLİVYA ÇOKULUSLU DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BREZİLYA FEDERATİF CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BAHAMALAR").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BUTAN KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BOTSVANA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BELARUS CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("BZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BELİZE").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KANADA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KONGO DEMOKRATİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KONGO CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İSVİÇRE KONFEDERASYONU").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FİLDİŞİ SAHİLİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ŞİLİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KAMERUN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÇİN HALK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KOLOMBİYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KOSTA RİKA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CS").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("SIRBİSTAN VE KARADAĞ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KÜBA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GÜNEY KIBRIS RUM YÖNETİMİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("CZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÇEK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ALMANYA FEDERAL CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DJ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("CİBUTİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("DANİMARKA KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("DOMİNİKA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("DOMİNİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("DZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("CEZAYİR DEMOKRATİK HALK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("EC").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("EKVATOR CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("EE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ESTONYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("EG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MISIR ARAP CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ER").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ERİTRE DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ES").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İSPANYA KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ET").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ETİYOPYA FEDERAL DEMOKRATİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("FI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FİNLANDİYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("FJ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FİJİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("FM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MİKRONEZYA FEDERE DEVLETLERİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("FR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FRANSA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GABON CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GB").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BÜYÜK BRİTANYA VE KUZEY İRLANDA BİRLEŞİK KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GRENADA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GÜRCİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GANA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GAMBİYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GİNE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GQ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("EKVATOR GİNESİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("YUNANİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GUATEMALA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GİNE-BİSSAU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("GY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GUYANA KOOPERATİF CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("HN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("HONDURAS CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("HR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("HIRVATİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("HT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("HAİTİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("HU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MACARİSTAN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ID").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ENDONEZYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İRLANDA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İSRAİL DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("HİNDİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IQ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("IRAK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İRAN İSLAM CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İZLANDA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("IT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İTALYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("JM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("JAMAİKA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("JO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÜRDÜN HAŞİMİ KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("JP").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("JAPONYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KENYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KIRGIZ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KAMBOÇYA KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KİRİBATİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KUZEY KIBRIS TÜRK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KOMORLAR BİRLİĞİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAİNT KİTTS VE NEVİS FEDERASYONU").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KOSOVA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KP").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KORE DEMOKRATİK HALK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KORE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KUVEYT DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("KZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KAZAKİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LAOS DEMOKRATİK HALK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LB").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LÜBNAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LC").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAİNT LUCİA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LİHTENŞTAYN PRENSLİĞİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SRİ LANKA DEMOKRATİK SOSYALİST CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LİBERYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LESOTHO KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LİTVANYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LÜKSEMBURG BÜYÜK DÜKALIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LV").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LETONYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("LY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LİBYA DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("M").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BİRLEŞİK MEKSİKA DEVLETLERİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FAS KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MC").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MONAKO PRENSLİĞİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MOLDOVA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ME").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KARADAĞ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MADAGASKAR CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MARŞAL ADALARI CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MAKEDONYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ML").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MALİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MYANMAR BİRLİĞİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BURMA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MOĞOLİSTAN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MORİTANYA İSLAM CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MALTA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MAURİTİUS CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MV").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MALDİVLER CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MALAVİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MALEZYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("MZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("MOZAMBİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NAMİBYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NİJER CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NİJERYA FEDERAL CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NİKARAGUA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("HOLLANDA KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NORVEÇ KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NP").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NEPAL FEDERAL DEMOKRATİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("NAURU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("NZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("YENİ ZELANDA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("OM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("UMMAN SULTANLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PANAMA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PERU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PAPUA YENİ GİNE BAĞIMSIZ DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FİLİPİNLER CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PAKİSTAN İSLAM CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("POLONYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("FİLİSTİN DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PORTEKİZ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PALAU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("PY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("PARAGUAY CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("QA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KATAR DEVLETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ROMANYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RS").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SIRBİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / BAŞKURDİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / ALTAY CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / ADIGE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / BURYAT CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / İNGUŞETYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KABARDİN-BALKARYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KALMIKYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KARAÇAY-ÇERKES CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KARELYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KOMİ CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / MARİ EL CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / MORDOVYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / SAHA CUMHURİYETİ (YAKUTİSTAN)").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / KUZEY OSETYA-ALANYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / TATARİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / TIVA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / UDMURT CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / HAKASYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / ÇUVAŞİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / DAĞISTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FED. / ÇEÇENİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUSYA FEDERASYONU").build(), 1);
        regionService.save(CreateRegionDto.builder().code("RW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("RUANDA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SUUDİ ARABİSTAN KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SB").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SOLOMON ADALARI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SC").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SEYŞELLER CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SUDAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GÜNEY SUDAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("İSVEÇ KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SİNGAPUR CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SI").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SLOVENYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SK").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SLOVAK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SL").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SİERRA LEONE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAN MARİNO CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SENEGAL CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SOMALİ FEDERAL CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SURİNAM CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ST").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAO TOME VE PRİNCİPE DEMOKRATİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SV").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("EL SALVADOR CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SURİYE ARAP CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("SZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SVAZİLAND KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TD").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÇAD CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TOGO CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TH").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TAYLAND KRALLIĞI").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TJ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TACİKİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TÜRKMENİSTAN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TUNUS CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TO").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TONGA KRALLIĞI").build(), 1);
        RegionService.turkiye = regionService.save(CreateRegionDto.builder().code("TR").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TÜRKİYE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TT").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TRİNİDAD VE TOBAGO CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TV").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TUVALU").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÇİN TAYVAN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("TZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("TANZANYA BİRLEŞİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("UA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("UKRAYNA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("UA").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("UKRAYNA SOV. SOS. CUM.").build(), 1);
        regionService.save(CreateRegionDto.builder().code("UG").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("UGANDA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("US").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("AMERİKA BİRLEŞİK DEVLETLERİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("UY").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("URUGUAY DOĞU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("UZ").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ÖZBEKİSTAN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("VA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("VATİKAN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("VC").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("SAİNT VİNCENT VE GRENADİNLER").build(), 1);
        regionService.save(CreateRegionDto.builder().code("VE").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BOLİVARCI VENEZUELA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("VN").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("VİETNAM SOSYALİST CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("VU").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("VANUATU CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("BİLİNMEYEN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("CABO VERDE CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ORTA AFRİKA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("DİĞER").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KUDÜS").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("LEFKOŞA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("KIRIM").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("DOĞU TİMOR DEMOKRATİK CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("BAYLÖRUSYAN (SSC)").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("ÇEKOSLOVAKYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("DEMOKRATİK ALMANYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("YUKARI VOLTA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("SOVYET SOS.CUM.BİR.").build(), 1);
        regionService.save(CreateRegionDto.builder().code("XX").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("ZAİRE").build(), 1);
        regionService.save(CreateRegionDto.builder().code("YE").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("DEMOKRATIK YEMEN").build(), 1);
        regionService.save(CreateRegionDto.builder().code("YM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("YEMEN CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("YU").enabled(false).regionTypeId(RegionTypeService.ulke.getId()).name("YUGOSLAVYA").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ZA").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("GÜNEY AFRİKA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ZM").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ZAMBİYA CUMHURİYETİ").build(), 1);
        regionService.save(CreateRegionDto.builder().code("ZW").enabled(true).regionTypeId(RegionTypeService.ulke.getId()).name("ZİMBABVE CUMHURİYETİ").build(), 1);

        defaultCities();
    }

    private void defaultCities() {
        regionService.save(CreateRegionDto.builder().name("ADANA").code("1").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ADIYAMAN").code("2").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("AFYONKARAHİSAR").code("3").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("AĞRI").code("4").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("AMASYA").code("5").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ANKARA").code("6").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ANTALYA").code("7").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ARTVİN").code("8").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("AYDIN").code("9").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BALIKESİR").code("10").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BİLECİK").code("11").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BİNGÖL").code("12").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BİTLİS").code("13").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BOLU").code("14").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BURDUR").code("15").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BURSA").code("16").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ÇANAKKALE").code("17").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ÇANKIRI").code("18").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ÇORUM").code("19").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("DENİZLİ").code("20").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("DİYARBAKIR").code("21").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("EDİRNE").code("22").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ELAZIĞ").code("23").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ERZİNCAN").code("24").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ERZURUM").code("25").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ESKİŞEHİR").code("26").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("GAZİANTEP").code("27").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("GİRESUN").code("28").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("GÜMÜŞHANE").code("29").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("HAKKARİ").code("30").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("HATAY").code("31").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ISPARTA").code("32").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MERSİN").code("33").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("İSTANBUL").code("34").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("İZMİR").code("35").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KARS").code("36").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KASTAMONU").code("37").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KAYSERİ").code("38").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KIRKLARELİ").code("39").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KIRŞEHİR").code("40").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KOCAELİ").code("41").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KONYA").code("42").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KÜTAHYA").code("43").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MALATYA").code("44").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MANİSA").code("45").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KAHRAMANMARAŞ").code("46").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MARDİN").code("47").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MUĞLA").code("48").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("MUŞ").code("49").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("NEVŞEHİR").code("50").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("NİĞDE").code("51").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ORDU").code("52").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("RİZE").code("53").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("SAKARYA").code("54").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("SAMSUN").code("55").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("SİİRT").code("56").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("SİNOP").code("57").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("SİVAS").code("58").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("TEKİRDAĞ").code("59").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("TOKAT").code("60").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("TRABZON").code("61").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("TUNCELİ").code("62").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ŞANLIURFA").code("63").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("UŞAK").code("64").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("VAN").code("65").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("YOZGAT").code("66").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ZONGULDAK").code("67").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("AKSARAY").code("68").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BAYBURT").code("69").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KARAMAN").code("70").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KIRIKKALE").code("71").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BATMAN").code("72").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ŞIRNAK").code("73").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("BARTIN").code("74").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("ARDAHAN").code("75").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("IĞDIR").code("76").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("YALOVA").code("77").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KARABÜK").code("78").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("KİLİS").code("79").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("OSMANİYE").code("80").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
        regionService.save(CreateRegionDto.builder().name("DÜZCE").code("81").parentId(RegionService.turkiye.getId()).regionTypeId(RegionTypeService.il.getId()).enabled(true).build(), 1);
    }


}
